export const FETCH_EVENTS_BEGINS = "FETCH_EVENTS_BEGINS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE"; 
export const GET_SINGLE_EVENT = "GET_SINGLE_EVENT"; 
export const CLEAN_SINGLE_EVENT = "CLEAN_SINGLE_EVENT"; 