export const FETCH_EVENTS_BEGINS = "FETCH_EVENTS_BEGINS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";
